### ISSUE TITLE
Feature request: Allow exporting of private keys even if the client isn't in sync

### ISSUE THREAD

**Issue by bsdhsr** [langerhans/multidoge#35]
Related to the issue being experienced in #34, this compounds tragically.

I've been trying for days to get MultiDoge to sync. Today I am considering moving the funds out, only to realize that 'the export private keys' functionality is only available if the client is synchronized.

It would be nice to have the option to export the private keys even if the client is lagging behind.

**Comment by AhmedDjoudi** [comment]
You can export the private keys even if it's out of sync. Also, you can consider trying this: [[solution] MultiDoge won't open… DON'T PANIC](http://www.reddit.com/r/multidoge/comments/29dpxk/solution_multidoge_wont_open_dont_panic/) or read along [the official MultiDoge subreddit](http://www.reddit.com/r/multidoge).
