### ISSUE TITLE
GUI not showing up after reboot in Kubuntu

### ISSUE THREAD

**Issue by Alko89** [langerhans/multidoge#38]
I have Kubuntu 14.10 with Plasma 4 desktop installed. Vhen starting multidoge.exe.jar for the first time, everything worked fine. After reboot the GUI isn't showing up anymore, but there is `/usr/bin/java -jar /home/aferlan/Documents/Cryptocurrency/MultiDoge-0.1.4/multidoge-exe.jar` proces running in the background.

**Comment by langerhans** [comment]
Try deleting `~/MultiDoge/multidoge.properties` and starting it again.

**Comment by Alko89** [comment]
Worked! Thanks! :+1:
