### ISSUE TITLE
Lost Data?!?!

### ISSUE THREAD

**Issue by bede01** [langerhans/multidoge#41]
hi i just updated to the latest version, when i opened it up everything was the same. Then about the third time i opened it my wallet had been deleted everywhere on my laptop. I had just started using this software and i had just over 2300 coins. If you could get back to me asap thanks.

**Comment by langerhans** [comment]
The wallet **never** deletes data _everywhere_. Your wallet files should be wherever you initially saved them, and even if not, you can always restore the backup you made as you were advised to :+1:  
Try looking at `C:\Users\YourUserName\AppData\Roaming\MultiDoge\` and see if your wallet files are there. They should be.

**Comment by bede01** [comment]
Yea i have gone there and tried to load up the wallets but when they synced
it was on 0 doge, no matter how many time i let it sync it dosen't work

**Comment by langerhans** [comment]
Please close MultiDoge go to the above mentioned folder again, find the `logs` folder there, delete the `multiage.log` file, then start MultiDoge again and let it run for a minute. Then attach the log file here.

**Comment by bede01** [comment]
ok i've done that but it still does not work.

**Comment by langerhans** [comment]
That was not supposed to fix it, you were supposed to attach that file here :|

**Comment by bede01** [comment]
oh, my mistake, but still nothing. it dosent matter anyways
