### ISSUE TITLE
Default Key Date is way in the past

### ISSUE THREAD

**Issue by h4ck3rm1k3** [langerhans/multidoge#53]
The issue is that the key createdAt date is 6 months in the past 2016-05-20T07:33:18Z and not today for keys created now. 

How to reproduce :

0. Download multidoge 0.1.7 http://multidoge.org/
from 
https://github.com/langerhans/multidoge/releases/download/v0.1.7/multidoge-0.1.7-linux.jar

1. Start and Create a new wallet
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513332941/xeip4gbpgucubqkzdrwc.png)
2. Select the new wallet
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513333022/ldy72js1kw50peyuvmff.png)
3. Select export wallet 
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513333094/ozqokz4eggurapmahiuw.png)
4. Export 
Turn off password for the test
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513333295/vi1qqzoimp8g8hkcrj3i.png)

5. Check the key
```mdupont@mdupont-Aspire-7750G:~/Downloads/dogecoin-1.10.0$ cat third.key 
# KEEP YOUR PRIVATE KEYS SAFE !
# Anyone who can read this file can spend your dogecoin.
#
# Format:
#   <Base58 encoded private key>[<whitespace>[<key createdAt>]]
#
#   The Base58 encoded private keys are the same format as
#   produced by the Satoshi client/ sipa dumpprivkey utility.
#
#   Key createdAt is in UTC format as specified by ISO 8601
#   e.g: 2011-12-31T16:42:00Z . The century, 'T' and 'Z' are mandatory
#
QTFj<redacted>EZPb5DU 2016-05-20T07:33:18Z

```

The issue is that the key createdAt date is 6 months in the past 2016-05-20T07:33:18Z and not today.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@h4ck3rm1k3st33m/default-key-date-is-way-in-the-past">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by langerhans** [comment]
Your blockchain was not synced at the time you did an export. Given this condition your observation is expected behavior. The comment here explains what happens: https://github.com/langerhans/multidoge/blob/master/src/main/java/org/multibit/file/PrivateKeysHandler.java#L317-L339

Thanks for the detailed report tho!

**Comment by h4ck3rm1k3** [comment]
I just wanted to import my keys like described here https://www.reddit.com/r/dogecoin/comments/1ycd5u/how_to_import_your_dogecoinqt_wallet_into/ 
what I was missing was this timestamp if I used the old one for my keys will take forever to import so really I want some instructions or comments in that file that might help the next poor guy.
