### ISSUE TITLE
Publisher of multidoge-0.1.7-windows-setup is not known

### ISSUE THREAD

**Issue by mmr11** [langerhans/multidoge#59]
Hello, I wanted to install multidoge (multidoge-0.1.7-windows-setup.exe) on my system (win 10 x64) but system tells the publisher of this setup file is unknown, so why the publisher is not known? and how is it safe to install?

**Comment by langerhans** [comment]
Windows says the because the code is not signed. I am the publisher. If you trust me then you can install it ;) The code is open source tho so if you wanted you could compile it yourself.
