### ISSUE TITLE
Dev: https://code.google.com/r/maxkeller90-dogecoinj-multibit/ doesn't exist anymore (turned down in 2016)

### ISSUE THREAD

**Issue by boutcher** [langerhans/multidoge#61]
Is this hosted somewhere else now?

**Comment by langerhans** [comment]
Yep, it's here: https://github.com/langerhans/dogecoinj-alice

**Comment by jmuia** [comment]
I probably have something wrong but the tests done seem to pass for `dogecoinj-alice` project

**Comment by langerhans** [comment]
Yeah they were never updated as this is legacy code. New wallets should use libdohj instead.
