### ISSUE TITLE
MultiDoge won't sync, can't access wallet

### ISSUE THREAD

**Issue by struex** [langerhans/multidoge#63]
Hi, I'm brand new to Dogecoin and hoping you can help me. I transferred Doge to a MultDoge wallet and can't get into the wallet. At first it showed the amount but wasn't spendable, still waiting on full confirmation. 12 hours later still wasn't spendable, though it showed as confirmed on the blockchain.

I then tried the Reset Blockchain and Transactions...and it simply failed after some time. I quit MultiDoge and then reopened to find no wallet listed whatsoever. I then opened the wallet manually by navigating to the .wallet file. Since then it took about 2 hours to get to 24% sync and is stuck there.

I did *not* export my private key to make backup before I tried Reset Blockchain, as I didn't know about that yet. The amount in this wallet is only about $20 but still this is upsetting. Is there any way for me to access my MultiDoge wallet now?

This is the URL for my one transaction
http://dogechain.info/tx/cf7bf914f0596fe16a09c5c8644aea9458c8ed064ebc19176c7cab058e61c33c

According to DogeChain my wallet did get the Doge:
http://dogechain.info/address/DBKTXCc8DtqjvXeNqV2A7WYSsr3doXLpnv

Thanks for your help!
@struex

**Comment by langerhans** [comment]
You might be able to kick the sync off again by restarting the wallet a few times. Also if your wallet is very large the sync will be very slow. That is sadly a known limitation of the upstream library we use. The easiest way forward would be exporting your private keys and importing them into a different wallet.

**Comment by struex** [comment]
Hi, thank you for your prompt reply. I was able to export my key and import to Dogechain wallet and everything is there.

All the best with MultiDoge, and thanks again.

**Comment by PrzemekSkw** [comment]
@langerhans Hi, I install yesterday Multidoge on linux and can't sync. I have 0 DOGE in my wallet. I restart many times but it don't help. Is any other way to fix this? Can I use another app to open my wallet?
Regards.
