### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by ghost** [langerhans/multidoge#65]
Hi !
I have a problem with font in MultiDoge. My MultiDoge looks like this:
https://imgur.com/jxV4Bfj

How can I fix it ? I'm using arch linux. Thanks for help !

**Comment by langerhans** [comment]
Could that be an old version? Fairly sure this was fixed. It was caused by Comic Sans not being available on all systems 🤔

**Comment by ghost** [comment]
I don't think that is old version. I downloaded it from official website.

**Comment by ghost** [comment]
I fixed it. All I had to do was download `ttf-ms-fonts` from aur.
