### ISSUE TITLE
Online sync low peers & very slow

### ISSUE THREAD

**Issue by Matthbo** [langerhans/multidoge#77]
Yes I know some other issues already addresses this but I haven't been able to find a proper solution.

I just started with crypto today and downloaded multidoge because it was the first wallet I could find for dogecoin.
I bought dogecoin and tried to transfer it to the multidoge wallet, the withdraw from the exchange wallet succeeded but nothing seemed to happen in multidoge.

I tried looking for solutions, but now it just seems like an abandoned project.

I am connect to 1 - 5 peers but the date of the last block is (when writing) still at 11 jan 2016 10:25.
Looking at other people with syncing problems mine doesn't even seem to try to stay connected with the network.

![image](https://user-images.githubusercontent.com/4380412/106311413-632c5200-6265-11eb-92e2-9cff5bab026e.png)

[multidoge.log](https://github.com/langerhans/multidoge/files/5895523/multidoge.log)

Can anyone help me with this or am I basically screwed and should just give up on receiving my withdrawn dogecoins?

**Comment by pavelantropov** [comment]
I'm having the same issue, and I already sent $200 worth of coins to that wallet. I believe that if someone could found the fix, much more people would buy the coins.

**Comment by pavelantropov** [comment]
8 fucking years ago people had this issue, and still, no one says how to fix it

**Comment by Matthbo** [comment]
A thing you could try is to export the private key (without setting password of export file) and see if other wallets work
The only thing I'm afraid of is if the receiving address will also be exported, because it not I'll just loose all coins

**Comment by Humancell** [comment]
No, you are not screwed.  As stated above, you can use "Tools -> Export Private Keys" to export them to a file.  If you do not set a password it will be in clear text.

NOTE: THIS PRIVATE KEY IS EVERYTHING YOU OWN! DO NOT SHARE IT ANYWHERE!

You could then go to another wallet, like FreeWallet.org and import the private key (not the file, but the funky long hash in the file) and that wallet can then access your account.  Now, FreeWallet is just an example, and they will sweep your coins into a wallet in their system, but that's no so bad if it's at least accessible.  I've also been looking for an alternative to getting the full Doge Core wallet since that is also a huge download.

**Comment by Humancell** [comment]
Also, I did find one thing that seemed to get some progress.  Reading this page:

https://github.com/langerhans/multidoge/blob/master/configuration.md

I closed MultiDoge, and then opened the config file mentioned above.

At the end of that config file I then pasted the peers list from here in the correct format:

https://www.reddit.com/r/dogecoin/comments/horyj0/dogecoin_blockchain/

`peers=173.255.204.124,107.150.52.74,136.244.101.227,167.172.211.76:22557,2001:19f0:6001:229b:5400:2ff:feeb:1f9e,2607:fb90:ce2d:7847:48ba:3763:6173:435f,45.32.66.136,50.220.121.211:6003,52.204.182.74,64.227.97.247:22557,68.108.211.35,68.195.18.155,73.168.22.226,73.253.117.17,73.61.6.1,76.102.39.163,97.77.231.85:9004,216.108.236.43,35.224.144.175,98.11.225.192,23.239.31.246,64.227.46.205,144.91.77.126,47.186.87.162,159.65.98.117
`

Save the config file, restart MultiDoge

Watching my log, at least I new see some activity ...

**Comment by Matthbo** [comment]
> No, you are not screwed. As stated above, you can use "Tools -> Export Private Keys" to export them to a file. If you do not set a password it will be in clear text.
> 
> NOTE: THIS PRIVATE KEY IS EVERYTHING YOU OWN! DO NOT SHARE IT ANYWHERE!
> 
> You could then go to another wallet, like FreeWallet.org and import the private key (not the file, but the funky long hash in the file) and that wallet can then access your account. Now, FreeWallet is just an example, and they will sweep your coins into a wallet in their system, but that's no so bad if it's at least accessible. I've also been looking for an alternative to getting the full Doge Core wallet since that is also a huge download.

Yeah I figured out how to import it into Exodus, so much easier and actually works, I immediately saw the new coin amount.
Tools -> Export Private Keys without encrypting the file with a password and then following [this guide](https://support.exodus.io/article/87-can-i-import-a-private-key) worked like a charm and I didn't have to wait for hours/days/weeks to scan the blockchain.

I say this is the best solution if you're done with the bad support for this program.

**Comment by Humancell** [comment]
Yeah ... I ended up starting the torrent on that second link that I posted, and if I don't see any progress I'll install the Doge Core Wallet and use the downloaded chain.  Should work better.

**Comment by OrelSokolov** [comment]
@Matthbo, I had the same issue day ago. 40$ to the moon, oh shit no, to the junk. I was pretty surprised...

**Comment by YokoTheDuke** [comment]
> Yeah ... I ended up starting the torrent on that second link that I posted, and if I don't see any progress I'll install the Doge Core Wallet and use the downloaded chain. Should work better.

Me too. Multidoge „Light“ Wallet did not download the actuall blockchain smooth. Look like it need weeks to make a actual update of the DogeCoin Blockchain. So I changed to Doge Core Wallet (Dogecoin.com) and following this Reddit post.

https://www.reddit.com/r/dogecoin/comments/l8b7d4/dogecoin_blockchain/

Download < 50 GB needs on 50Mbit wire roundabout 3 hours. Today I hope can get back my balance.

**Comment by brainmaniac** [comment]
I have the same issues as described above. I tried to add peers like @Humancell (@Humancell did it work for you?) suggests but without any success. So I want to try and move my doge. BUT it seems as if I have a password on my wallet 🙀 - was pretty sure I did not have a password on my wallet. So I have some questions:
 
 1. Can it be so that I don't have a password on my wallet but I need to sync the wallet before the password protection goes away (wishful thinking 😅 ) ?
 2. Is there a way to get the private keys from a multiDoge wallet with a password without using said password (again wishful thinking 😆 ??)
 3. What password breaking software do you recommend? 🤪

**Comment by sirapm** [comment]
I spent a couple of weeks getting Dogecoin Core to work. However, does not seem to support multiple wallets so I'm back to MultiDoge. However, as I now have a synced Docegoin core, I used the trick above to edit the preference file ad added my computer to the peer list and it is now syncing.  Currently I can only find two active peers on the Internet. Not good enough...

**Comment by brainmaniac** [comment]
@sirapm Did you get it to work with multidoge?

**Comment by sirapm** [comment]
Yes. But it is really slow and need some recoding for speeding it up.
Possible daily or weekly summary?
Cheers

**Comment by brainmaniac** [comment]
@sirapm o wow. Haven't got mine to work yet. I have two questions, would really appreciate if you have time to answer. 

1. Do you know if this syncing issue can show your wallet as locked while you are syncing? Thing is, mine is locked but I am 99% sure that I never had a password on it... This is also the case for my brother that I gave some coins. (we are talking about very little but it is still fun to get them :) ) - He never used password but now both of our wallets show up in the same way as OP is describing and they are locked. My hope is that once we are synced the lock will disappear. Could that happen?

2. How did you do it to get it to start downloading?

**Comment by MyNameIsBaron** [comment]
Try this: https://www.reddit.com/r/dogecoin/comments/mw6by9/dogecoin_core_syncing_for_ages_there_is_solution/

**Comment by brainmaniac** [comment]
@MyNameIsBaron Hi, but that is for core. I need to for MultiDoge. Thanks tho.

**Comment by btc2dogecom** [comment]
> @sirapm o wow. Haven't got mine to work yet. I have two questions, would really appreciate if you have time to answer.
> 
> 1. Do you know if this syncing issue can show your wallet as locked while you are syncing? Thing is, mine is locked but I am 99% sure that I never had a password on it... This is also the case for my brother that I gave some coins. (we are talking about very little but it is still fun to get them :) ) - He never used password but now both of our wallets show up in the same way as OP is describing and they are locked. My hope is that once we are synced the lock will disappear. Could that happen?
> 2. How did you do it to get it to start downloading?

yes, it is locked. even you did not do sync. it will show locked if it has password. so there is password on your wallet although you cant remember you set password. it wont disappear magically.
the multidoge is out of date. hard to get connected.
contact us if your problem unsolved and worth time on it. just recovered 360k+ on for a client
www.btc2doge.com

**Comment by ReverseControl** [comment]
@Matthbo The network should be orders of magnitude faster these days. But in any case it is recommended you bootstrap your wallet, i.e. download the ledger separately.

For Multidoge issues, you should address them direclty to the Multidoge project: https://github.com/langerhans/multidoge/issues.  Though the project seems to have been abandoned.

Follow this advice (save your private keys): https://github.com/langerhans/multidoge/issues/77#issuecomment-770096440

@patricklodder @rnicoll @michilumin We can close this one.
